### ISSUE TITLE
closing connections causes delay

### ISSUE THREAD

**Issue by mergingseas** [Rapidfacture/mongoose-multi#10]
I have 2 connections and when I disconnect I get the following message and a long pause before I get the shutting down message.  How can I close the connections and shutdown immediately?

[mongoose-multi] DB local disconnected, mongodb://*******************************************
[mongoose-multi] DB global disconnected, mongodb://********************************************

........(long pause...)

[mongoose-multi] shutting down application for restart: Try to reconnet DB.

**Comment by mergingseas** [comment]
@FelixFurtmayr 
Thanks for your response.  My current code is simply:

```
db.local.mongooseConnection.close();
db.global.mongooseConnection.close();
```
Ive got 2 databases, local and global and and I use the mongooseConnection.close() to close them after which I was getting the message

[mongoose-multi] DB local disconnected, mongodb://*******************************************
[mongoose-multi] DB global disconnected, mongodb://********************************************

........(long pause...)

[mongoose-multi] shutting down application for restart: Try to reconnet DB.

Our team thinks this is a very useful project and we'd love to keep testing it and possibly develop for it too.

Keep up the good work

**Comment by FelixFurtmayr** [comment]
"I believe I need to pass the auto_reconnect = false option"
