### ISSUE TITLE
what is best way to close the connections?

### ISSUE THREAD

**Issue by mergingseas** [Rapidfacture/mongoose-multi#8]
I am currently doing...

db.{db_name}.mongooseConnection.close();

is that the right way?

**Comment by FelixFurtmayr** [comment]
yes, as you will just use the mongoose function "mongoose.connection.close()".

db.{db_name}.mongooseConnection is just the original mongoose connection, just use it this way.

**Comment by mergingseas** [comment]
ok thanks!
