### ISSUE TITLE
DeprecationWarning: current URL string parser is deprecated

### ISSUE THREAD

**Issue by mhito** [Rapidfacture/mongoose-multi#9]
Hi! I get this simple warning knowing (I think) for all of us:

**(node:30216) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.**

I cant find any solution for this warning. Can anyone help with this?

Thanks.

Versions:
"mongoose": "^5.3.1"
"mongoose-multi": "^0.4.2"

Other dependecies:
"ini": "^1.3.5",
"uuid": "^3.3.2",
"ws": "^6.0.0"

**Comment by mhito** [comment]
**Ok, sorry**. maybe I should have read more the documentation, but in a quickly look for the proyect in Github and npm I could not find the solution. But here is:
To avoid the warning, you must create your **dbConfig.js** like this:
 
```
module.exports = {
    db: {
        online: {
            url: "mongodb://localhost:27017/auditoria",
            options : {useNewUrlParser: true} 
        },
        history: {
            url: "mongodb://otheHost:27017/db_arquitectura",
            options : {useNewUrlParser: true}
        }
    }
}
```

But in the docs only says:
```
module.exports = {
    db: {
        online: "mongodb://localhost:27017/auditoria",
        historico: "mongodb://192.168.244.75:27017/db_arquitectura"
    }
}
```

Reading the code in index.js I saw it:
```

if (typeof connection !== 'string') {
         options = connection.options || {};
         url = connection.url;
      }
startConnection(conName, url, schemaFile[conName], options);
```

**Comment by FelixFurtmayr** [comment]
Hi mhito,
thank you for the info. checkout the latest version on npm.
Any contribution to the code or the docs is also appreciated.

To your question:

```js
      var options = {}, url = connection;
      // obj holding url + options => transform
      if (typeof connection !== 'string') {
         options = connection.options || {};
         url = connection.url;
      }
```
This enables you to pass a simple string url, or an object with options to mongoose-multi.
So both version above should be valid. I will add this to the docs

Regards Felix
